### ISSUE TITLE
browser_cookie3 not a thing?

### ISSUE THREAD

**Issue by OnionKinq** [l-ust/beamed#1]
Traceback (most recent call last):
  File "beamed.py", line 1, in <module>
    import browser_cookie3 as steal, requests, base64, random, string, subprocess, zipfile, shutil, dhooks, os, re, sys, sqlite3, json
ModuleNotFoundError: No module named 'browser_cookie3'

**Comment by l-ust** [comment]
hey, sorry for the late response; i wasn't all that active last night. 
this is more or less an easy fix, so i'm here to help: i actually haven't got down to including a 'requirements.txt': but that'll be uploaded as a file & included with instructions in the readme.md soon 

you'll want to open a cmd prompt, (make sure Python is installed to PATH) & run
 `'pip install browser_cookie3'`

that should fix your error, let me know & respond if you have anymore errors with the script.

if it fixed your error, & you're satisfied w the script : a star/follow would be appreciated 

-lust
