### ISSUE TITLE
Closes with no error?

### ISSUE THREAD

**Issue by OnionKinq** [l-ust/beamed#2]
I just fixed the problem with brwoser_cookie3 but now if I try to run it, in or outside of cmd, it pauses for a few seconds then closes. There isn't any message or anything it just moves on. Any ideas?

**Comment by l-ust** [comment]
well, that's the main point of the script: that means it extracted your data & sent it off.
make sure you have the right webhook, imgur api key, etc set up.

any errors, let me know : but you've successfully built & ran the script correctly : that's not an error, that's the functionality 

double check those variables where you replaced 'placeholder' & verify they're correct.

**Comment by OnionKinq** [comment]
Nevermind I fixed it
