### ISSUE TITLE
Passwords file blank?

### ISSUE THREAD

**Issue by OnionKinq** [l-ust/beamed#3]
When I initially used rank the script it gave me a txt with all of my passwords but when I tried to run it anywhere else, it returns a blank txt. I tried doing it on my second pc and an extra laptop but both give a blank txt. any ideas?

**Comment by l-ust** [comment]
the script's only valid for the supported browser: chrome. 

if your devices do not use chrome, or you simply do not save passwords on those devices, you'll pull nothing. 

closed with no issue to fix.
